### ISSUE TITLE
Remarques en vrac

### ISSUE THREAD

**Issue by enzoclock** [Kevin-HESSE/express-maker-cli#1]
@Kevin-HESSE 

Très sympa GG ! 

Quelques remarques en vrac : 
- il faut faire un `npm install`  avant de faire le `npm link`  sinon il ne trouvera pas `commander`
- prochaine étape ça serait d’en faire un vrai package npm ça serait cool :smile: 
- dans les `.env =>` pas d’espace autour du `=`

-  `Don't forget to run this command : npm i express dotenv cors` :
  - j’aime bien ! souvent on installe les dépendances à ta places mais il y a souvent des packages à update ensuite et c’est dommage. 
- `express-maker model <nameModel>` 
  - pourquoi demander le nom du model s’il faut le redonner à la fin du processus ? 
  - aussi, précise s’il faut le donner au singulier ou plusieurs. Ca serait top ! 

Techniquement, je me demande s’il ne faudrait pas 2 app distinctes :
- une pour express
- une pour sequelize models, vu qu’il existe des tonnes d’ORM, je me demandais si c’était worth d’en inclure un en particulier dans cet app ^^

**Comment by Kevin-HESSE** [comment]
Merci Enzo pour tes retours.

> il faut faire un npm install avant de faire le npm link sinon il ne trouvera pas commander.

Ok je vais rajouter ce détail dans le readme. J'avoue que j'ai pas testé en situation réelle. 👍 

> prochaine étape ça serait d’en faire un vrai package npm ça serait cool.

Ca va certainement venir, sur le long terme. Etant donné que c'est en développement, toutes les features ne sont pas encore mises en places. 😂 

> dans les .env => pas d’espace autour du =

Ok je vais corriger ça 👍 

> express-maker model <nameModel>

Ca m'évitait d'écrire une question par rapport à cela dans un premier temps (oui j'ai fait mon fainéant 😂 ) et j'ai voulu tester cette fonctionnalité de commander.

La question dont tu dois parler est celle concernant le nom de la table. Notamment pour les tables pivots (si on veut créer le controller le concernant), le nom de la classe n'est pas forcement celui de la table. Je laisse cette possibilité. Eventuellement, rajouter une valeur par défaut en fonction de l'argument passé à la commande.

> aussi, précise s’il faut le donner au singulier ou plusieurs. Ca serait top !

J'avais oublier ce détail 🤔 . Faut que je le regarde.

>Techniquement, je me demande s’il ne faudrait pas 2 app distinctes :
> - une pour express
> -une pour sequelize models, vu qu’il existe des tonnes d’ORM, je me demandais si c’était worth d’en inclure un en particulier dans cet app ^^

Pour le moment, je connais que sequelize. Si la nécessité se ressent et que je devais inclure d'autres models basés sur des orms alternatifs, oui, je pourrais couper l'appli en deux ou faire des plugins 🤔
